version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $user
      POSTGRES_PASSWORD: $password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8090:8090"
volumes:
  data: